In [27]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# --- 경로 설정 ---
# ipynb파일은 getcwd()함수를 이용해서 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\ktx_pipeline'

In [28]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'ktx_raw.csv') # 경로를 합침
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\ktx_pipeline\\input\\ktx_raw.csv'

In [29]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'ktx_lot.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\ktx_pipeline\\output\\ktx_lot.csv'

In [30]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/ktxdb'

In [32]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

  고속철도명  철도운영기관  노선명  순번   역명                    주소
0   KTX  한국철도공사  경부선   1   행신   경기도 고양시 덕양구 소원로 102
1   KTX  한국철도공사  경부선   2   서울    서울특별시 용산구 한강대로 405
2   KTX  한국철도공사  경부선   3  영등포    서울특별시 영등포구 경인로 846
3   KTX  한국철도공사  경부선   4   광명       경기도 광명시 광명역로 21
4   KTX  한국철도공사  경부선   5   수원  경기도 수원시 팔달구 덕영대로 924

In [46]:
do_list = ['서울', '경기', '충청', '강원', '경상', '전라']

def get_do(adr):

    for do in do_list:
        if do in adr:
            return do
        
    if '서울' in adr :
        return '서울'
    elif '경기' in adr:
        return '경기'
    elif '충남' in adr or '충북' in adr or '대전' in adr:
        return '충청'
    elif '대구' in adr or '경북' in adr or '경남' in adr or '부산' in adr or '울산' in adr:
        return '경상'
    elif '전남' in adr or '전북' in adr or '광주' in adr:
        return '전라'
    elif '강원' in adr:
        return '강원'
    else:
        return '기타'
        
if '주소' in df_raw.columns:
    df_raw['구분'] = df_raw['주소'].apply(get_do)

In [47]:
df_raw.head(20)

   고속철도명  철도운영기관  노선명  순번       역명                         주소  구분
0    KTX  한국철도공사  경부선   1       행신        경기도 고양시 덕양구 소원로 102  경기
1    KTX  한국철도공사  경부선   2       서울         서울특별시 용산구 한강대로 405  서울
2    KTX  한국철도공사  경부선   3      영등포         서울특별시 영등포구 경인로 846  서울
3    KTX  한국철도공사  경부선   4       광명            경기도 광명시 광명역로 21  경기
4    KTX  한국철도공사  경부선   5       수원       경기도 수원시 팔달구 덕영대로 924  경기
5    KTX  한국철도공사  경부선   6     천안아산         충남 아산시 배방읍 희망로 100  충청
6    KTX  한국철도공사  경부선   7       오송  충북 청주시 흥덕구 오송읍 오송가락로 123   충청
7    KTX  한국철도공사  경부선   8       대전              대전 동구 중앙로 215  충청
8    KTX  한국철도공사  경부선   9     김천구미         경북 김천시 남면 혁신 1로 51  경상
9    KTX  한국철도공사  경부선  10      서대구             대구시 서구 와룡로 527  경상
10   KTX  한국철도공사  경부선  11      동대구             대구 동구 동대구로 550  경상
11   KTX  한국철도공사  경부선  12       포항           경북 포항시 흥해읍 포항역로1  경상
12   KTX  한국철도공사  경부선  13       경주         경북 경주시 건천읍 경주역로 80  경상
13   KTX  한국철도공사  경부선  14  울산(통도사)        울산 울주군 삼남면 울산역로 177  경상
14   KTX  한국철도공사  경부선  15       경산               경북 경산시 중앙로 1  경상
15   KTX  한국철도공사  경부선  16       밀양              경남 밀양시 중앙로 62  경상
16   KTX  한국철도공사  경부선  17       물금         경남 양산시 물금읍 황산로 347  경상
17   KTX  한국철도공사  경부선  18       구포             부산 북구 구포만세길 82  경상
18   KTX  한국철도공사  경부선  19       부산            부산시 동구 중앙대로 206  경상
19   KTX  한국철도공사  호남선   1       행신        경기도 고양시 덕양구 소원로 102  경기

In [48]:
# --- 결측치 확인 ---
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견')
    print(null_counts[null_counts > 0])
else:
    print('결측치 없음')

결측치 없음

In [49]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)  # str로 형변환

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : ktxdb / table : {table_name}')

TABLE_NAME = 'ktx_raw'

save_to_postgresql(df_raw, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료! 102행
DB : ktxdb / table : ktx_raw

In [50]:
df_raw.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_raw):,}행 x {len(df_raw.columns)}열')

CSV 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\ktx_pipeline\output\ktx_lot.csv
크기: 102행 x 7열

In [52]:
print('=' * 80)
print('KTX 역 정보 수집 파이프라인 결과')
print('=' * 80)
print('수집 방식 : 공공데이터포털 - KTX API')
print(f'컬럼 수 : {len(df_raw.columns)}개')
print(f'csv 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치 : ktxdb.{TABLE_NAME}')
print('=' * 80)

================================================================================
KTX 역 정보 수집 파이프라인 결과
================================================================================
수집 방식 : 공공데이터포털 - KTX API
컬럼 수 : 7개
csv 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\ktx_pipeline\output\ktx_lot.csv
DB 저장 위치 : ktxdb.ktx_raw
================================================================================